run("Fluorescent Cells (400K)");
run("Split Channels");
selectWindow("RGB_Cell (green)");
run("8-bit");
setAutoThreshold("Otsu");
run("Convert to Mask");
run("Create Selection");
run("Duplicate...", "title=Mask");
imageCalculator("AND create", "RGB_Cell (green)", "Mask");
selectWindow("Result of RGB_Cell (green)");
run("Analyze Particles...", "size=50-Infinity display add");
